/** 
 * Generated by KissMDA - Simple Java Cartridge - kissmda-cartridges-simple-java.
 * KissMDA: http://kissmda.org
 *  
 * DO NOT EDIT this file manually! All changes will be overwritten by next generation!
 *  
 * Generation date: Mon Dec 25 00:44:29 IST 2017.
 */
package com.mukund.frm.server.exception;
public class CreatePersonException extends CreateException {
	private static final long serialVersionUID = 1L;
	public CreatePersonException() {
	}
	public CreatePersonException(Throwable cause) {
		super(cause);
	}
	public CreatePersonException(String message) {
		super(message);
	}
	public CreatePersonException(String message, Throwable cause) {
		super(message, cause);
	}
}
