/** 
 * Generated by KissMDA - Simple Java Cartridge - kissmda-cartridges-simple-java.
 * KissMDA: http://kissmda.org
 *  
 * DO NOT EDIT this file manually! All changes will be overwritten by next generation!
 *  
 * Generation date: Mon Dec 25 00:44:28 IST 2017.
 */
package com.mukund.frm.server.service;
import com.mukund.frm.server.domain.Address;
import com.mukund.frm.server.domain.Person;
import com.mukund.frm.server.exception.CreatePersonException;
import com.mukund.frm.server.exception.FinderException;

import java.util.Collection;
public interface PersonService {
	Person createAddressFromPerson(Address address, Person person)
			throws CreatePersonException;
	Collection<Person> findAllPersons(Integer start, Integer length)
			throws FinderException;
}
